# Generated by Django 5.2.11 on 2026-02-12 15:51

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('INDEX', 'Stock Index'), ('COMMODITY', 'Commodity'), ('CRYPTO', 'Cryptocurrency')], max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexConstituent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('search_vector', models.TextField(blank=True, null=True)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(default='1d', max_length=10)),
                ('timestamps', models.JSONField(default=list)),
                ('opens', models.JSONField(default=list)),
                ('highs', models.JSONField(default=list)),
                ('lows', models.JSONField(default=list)),
                ('closes', models.JSONField(default=list)),
                ('volumes', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('average_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unrealized_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unrealized_pl_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('change_percent', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('valid_period', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('indicators', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('SMA', 'Simple Moving Average'), ('EMA', 'Exponential Moving Average'), ('RSI', 'Relative Strength Index'), ('MACD', 'Moving Average Convergence Divergence'), ('BB', 'Bollinger Bands'), ('STOCH', 'Stochastic Oscillator')], max_length=20)),
                ('period', models.IntegerField()),
                ('value', models.JSONField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance_history', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Watchlist', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('price_alert_enabled', models.BooleanField(default=False)),
                ('alert_threshold_above', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('alert_threshold_below', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('ABOVE', 'Price Above'), ('BELOW', 'Price Below'), ('CROSS_ABOVE', 'Cross Above'), ('CROSS_BELOW', 'Cross Below')], max_length=20)),
                ('target_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('commodity_type', models.CharField(choices=[('PRECIOUS', 'Precious Metal'), ('BASE', 'Base Metal'), ('ENERGY', 'Energy'), ('AGRICULTURAL', 'Agricultural')], max_length=50)),
                ('unit', models.CharField(default='oz', max_length=20)),
                ('purity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('coin_gecko_id', models.CharField(blank=True, max_length=50, null=True)),
                ('circulating_supply', models.BigIntegerField(blank=True, null=True)),
                ('total_supply', models.BigIntegerField(blank=True, null=True)),
                ('max_supply', models.BigIntegerField(blank=True, null=True)),
                ('market_cap_rank', models.IntegerField(blank=True, null=True)),
            ],
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('calculation_method', models.CharField(default='Market Cap Weighted', max_length=50)),
                ('base_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('base_date', models.DateField(blank=True, null=True)),
            ],
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('company_name', models.CharField(max_length=200)),
                ('sector', models.CharField(db_index=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('search_vector', models.TextField(blank=True, null=True)),
            ],
            bases=('assets.asset',),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['symbol', 'asset_type'], name='assets_asse_symbol_8a88ff_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='assets_asse_created_763da7_brin', pages_per_range=16),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('symbol', 'asset_type'), name='unique_asset_symbol_type'),
        ),
        migrations.AddField(
            model_name='alert',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AddField(
            model_name='newsheadline',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='ohlcv',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='portfolioholding',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='technicalindicator',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioholding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.userportfolio'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.watchlist'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='assets',
            field=models.ManyToManyField(blank=True, through='assets.WatchlistItem', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='indexconstituent',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.index'),
        ),
        migrations.AddIndex(
            model_name='stocks',
            index=models.Index(fields=['sector', 'industry'], name='assets_stoc_sector_6c04bb_idx'),
        ),
        migrations.AddIndex(
            model_name='stocks',
            index=models.Index(fields=['market_cap'], name='assets_stoc_market__1182ff_idx'),
        ),
        migrations.AddField(
            model_name='indexconstituent',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.stocks'),
        ),
        migrations.AddField(
            model_name='index',
            name='constituents',
            field=models.ManyToManyField(blank=True, through='assets.IndexConstituent', to='assets.stocks'),
        ),
        migrations.AddIndex(
            model_name='newsheadline',
            index=models.Index(fields=['-published_at'], name='assets_news_publish_ad6df1_idx'),
        ),
        migrations.AddIndex(
            model_name='newsheadline',
            index=models.Index(fields=['asset', '-published_at'], name='assets_news_asset_i_a4e487_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcv',
            index=models.Index(fields=['asset', 'timeframe', '-last_updated'], name='assets_ohlc_asset_i_9ca115_idx'),
        ),
        migrations.AddConstraint(
            model_name='ohlcv',
            constraint=models.UniqueConstraint(fields=('asset', 'timeframe'), name='unique_asset_timeframe'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['asset', 'timestamp'], name='assets_pric_asset_i_dd030a_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='assets_pric_timesta_7702ea_brin', pages_per_range=32),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(fields=('asset', 'timestamp'), name='unique_asset_timestamp'),
        ),
        migrations.AddIndex(
            model_name='technicalindicator',
            index=models.Index(fields=['asset', 'indicator_type', '-timestamp'], name='assets_tech_asset_i_63eb1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalindicator',
            unique_together={('asset', 'indicator_type', 'period', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='userportfolio',
            index=models.Index(fields=['user', '-created_at'], name='assets_user_user_id_f8b4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioholding',
            index=models.Index(fields=['portfolio', 'asset'], name='assets_port_portfol_c29fcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioholding',
            unique_together={('portfolio', 'asset')},
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['watchlist', '-added_at'], name='assets_watc_watchli_50308a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('watchlist', 'asset')},
        ),
        migrations.AddIndex(
            model_name='indexconstituent',
            index=models.Index(fields=['index', 'weight'], name='assets_inde_index_i_bf6387_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indexconstituent',
            unique_together={('index', 'stock')},
        ),
    ]
