# Generated by Django 5.2.11 on 2026-04-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['symbol']},
        ),
    ]
